# Generated by Django 2.2.28 on 2025-03-07 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingID', models.CharField(max_length=8, unique=True)),
                ('date', models.DateField()),
                ('numOfStudents', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('subjects', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TutorID', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=5000)),
                ('subjects', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReviewID', models.CharField(max_length=8, unique=True)),
                ('rating', models.IntegerField()),
                ('content', models.CharField(max_length=5000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GUTors_app.Student')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GUTors_app.Booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GUTors_app.Tutor'),
        ),
    ]
