# Generated by Django 2.2.28 on 2025-03-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUTors_app', '0002_auto_20250326_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='avatar.jpg', upload_to='profile_images'),
        ),
    ]
