# Generated by Django 2.2.28 on 2025-03-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUTors_app', '0003_auto_20250327_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringsession',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_images/avatar.jpg', upload_to='profile_images'),
        ),
    ]
